# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-14 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
