# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-27 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0004_remove_source_source_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
    ]
